image: alpine/edge
packages:
  - rsync
  - git
  - hugo
sources:
  - https://git.sr.ht/~redstrate/redstrate.com
secrets:
  - b748582a-5d31-4fe8-94d6-4a63035e97aa
tasks:
  - build: |
      cd redstrate.com
      hugo
  - deploy: |
      cd redstrate.com
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      rsync -e 'ssh -p 38901' -Wvr public/ deploy@ryne.moe:/srv/http/redstrate.com
