baseURL: 'https://redstrate.com/'
copyright: 'This content is licensed under a Creative Commons Attribution-ShareAlike 4.0.'
disableHugoGeneratorInject: true
enableGitInfo: true
enableRobotsTXT: true
summarylength: 15
disableKinds:
- taxonomy

markup:
  tableOfContents:
    ordered: true
    startLevel: 1
  goldmark:
    parser:
        wrapStandAloneImageWithinParagraph: false

title: '~redstrate'
theme: 'red'
timeZone: 'UTC'

pagination:
    pagerSize: 20

params:
  description: "My personal corner of the Internet!"
  github_username: "redstrate"
  invent_username: "redstrate"
  isso_url: "comments.redstrate.com"
  geekring_site_id: 227
  gitlab_username: "redstrate"
  profile_picture: "/rss-image.png"
  images:
  - rss-image.png
  author: 'redstrate'
  fediverse_url: "@redstrate@mastodon.art"
  image_host: "https://images.redstrate.com"
  kofi_username: 'redstrate'
  enable_koring: true

permalinks:
  blog: 'blog/:year/:month/:title/'
  art: 'art/:year/:month/:slugorfilename'
  arttags: 'art/tags/:title'
  characters: 'art/characters/:slugorfilename'
  tags: 'blog/tags/:title'
  series: 'blog/series/:title'
  projtags: 'software/tags/:title'

taxonomies:
  series: 'series'
  tag: 'tags'
  arttag: 'arttags'
  character: 'characters'
  projtag: 'projtags'

menu:
  main:
  - name: 'Home'
    params:
    - img: 'icons/home.svg'
    url: ''
    weight: -1
  - name: 'Blog'
    params:
    - img: 'icons/blog.svg'
    url: 'blog'
    weight: 1
  - name: 'Art'
    params:
    - img: 'icons/art.svg'
    url: 'art'
    weight: 2
  - name: 'Music'
    params:
    - img: 'icons/music.svg'
    url: 'music'
    weight: 3
  - name: 'Software'
    params:
    - img: 'icons/software.svg'
    url: 'software'
    weight: 4
  - name: 'Talks'
    params:
    - img: 'icons/talks.svg'
    url: 'talks'
    weight: 5
  - name: 'Games'
    params:
    - img: 'icons/game.svg'
    url: 'https://redstrate.itch.io/'
    weight: 6
  - name: 'Videos'
    params:
    - img: 'icons/video.svg'
    url: 'https://tube.ryne.moe/@redchannel'
    weight: 7
  - name: 'Shrines'
    params:
    - img: 'icons/shrines.svg'
    url: 'shrines'
    weight: 8
  - name: 'Links'
    params:
    - img: 'icons/links.svg'
    url: 'links'
    weight: 9
  - name: 'Guestbook'
    params:
    - img: 'icons/guestbook.svg'
    url: 'guestbook'
    weight: 10
  - name: 'Contact'
    params:
    - img: 'icons/contact.svg'
    url: 'contact'
    weight: 11
  - name: 'About'
    params:
    - img: 'icons/about.svg'
    url: 'about'
    weight: 12
  footer:
  - name: 'Feeds'
    url: 'feeds'
    weight: -1
  - name: 'Imprint'
    url: 'imprint'
    weight: 2
  - name: 'Accessibility'
    url: 'accessibility'
    weight: 3
  badges:
  - name: 'CC NC SA'
    params:
    - img: 'by-nc-sa.webp'
    url: 'by-nc-sa.webp'
    weight: -1
  - name: 'RSS Feed'
    params:
    - img: 'rssbanner.webp'
    url: 'rssbanner.webp'
    weight: 1
  - name: 'Powered by Gentoo'
    params:
    - img: 'gentoo-badge2.webp'
    url: 'gentoo-badge2.webp'
    weight: 2
  - name: 'Evangelion'
    params:
    - img: 'nerv_button.webp'
    url: 'nerv_button.webp'
    weight: 3
  otherbadges:
  - name: 'Neocreatives Webring'
    params:
    - img: 'neocreatives.gif'
    url: 'http://neocreatives.byethost5.com/directory.php'
    weight: 4
  socials:
  - name: 'Mastodon'
    params:
    - img: 'mastodon.webp'
    url: 'https://mastodon.art/@redstrate'
    weight: -1
  - name: 'Newgrounds'
    params:
    - img: 'newgrounds.webp'
    url: 'https://redstrate.newgrounds.com'
    weight: 1
  - name: 'Pixiv'
    params:
    - img: 'pixiv.webp'
    url: 'https://www.pixiv.net/en/users/58118005'
    weight: 2
  - name: 'Codeberg'
    params:
    - img: 'codeberg.webp'
    url: 'https://codeberg.org/redstrate'
    weight: 3
  - name: 'GitHub'
    params:
    - img: 'github.webp'
    url: 'https://github.com/redstrate'
    weight: 4
  - name: 'Ko-fi'
    params:
    - img: 'kofi.webp'
    url: 'https://ko-fi.com/redstrate'
    weight: 4

defaultContentLanguage: 'en'
languageCode: 'en-us'
defaultContentLanguageInSubdir: false

languages:
    en:
        languageName: English
    tok:
        contentDir: content/tok
        languageName: Toki Pona
        disabled: true
    de:
        contentDir: content/de
        languageName: German
        disabled: true
    jp:
        languageName: Japanese
        menus:
            main:
            - name: 'トップ'
              params:
              - img: 'icons/home.svg'
              url: ''
              weight: -1
            - name: '芸術'
              params:
              - img: 'icons/art.svg'
              url: 'art'
              weight: 2
            socials:
            - name: 'pixiv'
              params:
              - img: 'pixiv.webp'
              url: 'https://www.pixiv.net/en/users/58118005'
              weight: 2
