baseURL = 'https://redstrate.com/'
languageCode = 'en-us'
title = '~redstrate'
theme = 'red'
enableGitInfo = true
enableRobotsTXT = true

[params]
    description = "My personal corner of the Internet!"

copyright = 'This content is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0.'
[author]
    name = 'redstrate'

[permalinks]
  blog = 'blog/:year/:month/:title/'

[menu]
    [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = -1

    [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    url = '/blog'
    weight = 1

    [[menu.main]]
    identifier = 'art'
    name = 'Art'
    url = '/art'
    weight = 2

    #[[menu.main]]
    #identifier = 'photos'
    #name = 'Photos'
    #url = '/photos'
    #weight = 3

    [[menu.main]]
    identifier = 'music'
    name = 'Music'
    url = '/music'
    weight = 4

    [[menu.main]]
    identifier = 'software'
    name = 'Software'
    url = '/software'
    weight = 6

    [[menu.main]]
    identifier = 'downloads'
    name = 'Downloads'
    url = '/downloads'
    weight = 7

    [[menu.main]]
    identifier = 'extra'
    name = 'Extras'
    url = '/extra'
    weight = 8

    [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about'
    weight = 9

[outputs]
    home = ["HTML"]
    page = ["HTML"]
    section = ["HTML", "RSS"]
