baseURL: 'https://redstrate.com/'
copyright: 'This content is licensed under a Creative Commons Attribution-ShareAlike 4.0.'
defaultContentLanguage: 'en'
disableHugoGeneratorInject: true
enableGitInfo: true
enableRobotsTXT: true
languageCode: 'en-us'
summarylength: 15
disableKinds:
- taxonomy

markup:
  tableOfContents:
    ordered: true
    startLevel: 1
  goldmark:
    parser:
        wrapStandAloneImageWithinParagraph: false

title: '~redstrate'
theme: 'red'
timeZone: 'UTC'
paginate: 20

params:
  description: "My personal corner of the Internet!"
  github_username: "redstrate"
  invent_username: "redstrate"
  isso_url: "comments.redstrate.com"
  geekring_site_id: 227
  gitlab_username: "redstrate"
  profile_picture: "/rss-image.png"
  images:
  - rss-image.png

author:
  name: 'redstrate'
  email: 'josh@redstrate.com'

permalinks:
  blog: 'blog/:year/:month/:title/'
  art: 'art/:year/:month/:slugorfilename'
  arttags: 'art/tags/:title'
  characters: 'art/characters/:title'
  tags: 'blog/tags/:title'
  series: 'blog/series/:title'
  projtags: 'software/tags/:title'

taxonomies:
  series: 'series'
  tag: 'tags'
  arttag: 'arttags'
  character: 'characters'
  projtag: 'projtags'

menu:
  main:
  - name: 'Home'
    url: '/'
    weight: -1
  - name: 'Blog'
    url: '/blog'
    weight: 1
  - name: 'Art'
    url: '/art'
    weight: 2
  - name: 'Music'
    url: '/music'
    weight: 3
  - name: 'Software'
    url: '/software'
    weight: 4
  - name: 'Games'
    url: 'https://redstrate.itch.io/'
    weight: 5
  - name: 'Videos'
    url: 'https://tube.ryne.moe/@redchannel'
    weight: 6
  - name: 'Shrines'
    url: '/shrines'
    weight: 7
  - name: 'Downloads'
    url: '/downloads'
    weight: 8
  - name: 'Links'
    url: '/links'
    weight: 9
  - name: 'Guestbook'
    url: '/guestbook'
    weight: 10
  - name: 'About'
    url: '/about'
    weight: 11
  retromain:
  - name: 'Home'
    url: '/'
    weight: -1
  - name: 'Blog'
    url: '/blog'
    weight: 1
  - name: 'Art'
    url: '/art'
    weight: 2
  - name: 'Software'
    url: '/software'
    weight: 4
  - name: 'Downloads'
    url: '/downloads'
    weight: 6
  - name: 'Links'
    url: '/links'
    weight: 7
  - name: 'About'
    url: '/about'
    weight: 9
  footer:
  - name: 'Blog Feed'
    url: '/blog/index.xml'
    weight: -1
  - name: 'Art Feed'
    url: '/art/index.xml'
    weight: 1
  - name: 'Imprint'
    url: '/imprint'
    weight: 2
  badges:
  - name: 'CC NC SA'
    url: 'by-nc-sa.webp'
    weight: -1
  - name: 'RSS Feed'
    url: 'rssbanner.webp'
    weight: 1
  - name: 'Powered by Gentoo'
    url: 'gentoo-badge2.webp'
    weight: 2
  - name: 'Evangelion'
    url: 'nerv_button.webp'
    weight: 3
