baseURL = 'https://redstrate.com/'
languageCode = 'en-us'
title = '~redstrate'
theme = 'red'
enableGitInfo = true
enableRobotsTXT = true

[params]
    description = "My personal corner of the Internet!"

copyright = 'This content is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0.'
[author]
    name = 'redstrate'

[permalinks]
  blog = 'blog/:year/:month/:title/'
  art = 'art/:year/:month/:slugorfilename'
  arttags = 'art/tags/:title'
  characters = 'art/characters/:title'
  characters_listpath = "art/characters/"

[taxonomies]
  series = 'series'
  tag = 'tags'
  arttag = 'arttags'
  character = 'characters'

[menu]
    [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = -1

    [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    url = '/blog'
    weight = 1

    [[menu.main]]
    identifier = 'art'
    name = 'Art'
    url = '/art'
    weight = 2

    #[[menu.main]]
    #identifier = 'photos'
    #name = 'Photos'
    #url = '/photos'
    #weight = 3

    [[menu.main]]
    identifier = 'music'
    name = 'Music'
    url = '/music'
    weight = 4

    [[menu.main]]
    identifier = 'software'
    name = 'Software'
    url = '/software'
    weight = 6

    [[menu.main]]
    identifier = 'videos'
    name = 'Videos'
    url = 'https://tube.ryne.moe/@redchannel'
    weight = 7

    [[menu.main]]
    identifier = 'downloads'
    name = 'Downloads'
    url = '/downloads'
    weight = 8

    [[menu.main]]
    identifier = 'extra'
    name = 'Extras'
    url = '/extra'
    weight = 9

    [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about'
    weight = 10

[outputs]
    home = ["HTML"]
    page = ["HTML"]
    section = ["HTML", "RSS"]
