name = "red"
license = "MIT"
licenselink = "https://github.com/redstrate/redstrate.com/tree/main/themes/red/LICENSE"
description = "Custom Hugo theme for use on redstrate.com"
homepage = "https://redstrate.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "redstrate <josh@redstrate.com>"
  homepage = "https://redstrate.com/"
